=== shirolab/roach2pcp/pcp/testing/tonelists/xmlschema_tbexample.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="tonefile">
  <xs:complexType>
    <xs:sequence>
    <xs:element name="tonelist" maxOccurs="unbounded">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="KID" maxOccurs="unbounded">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="freq" type="xs:float"/>
                <xs:element name="freqUnit">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                     <xs:enumeration value="Hz"/>
                      <xs:enumeration value="kHz"/>
                      <xs:enumeration value="MHz"/>
                      <xs:enumeration value="GHz"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:element>
                <xs:element name="power" type="xs:float"/>
                <xs:element name="powerUnit">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                     <xs:enumeration value="dBW"/>
                     <xs:enumeration value="dBm"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:element>
                <xs:element name="Qfactor" type="xs:float"/>
              </xs:sequence>
              <xs:attribute name="ID" type="xs:string" use="required"/>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
        <xs:attribute name="ID" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="date" type="xs:date"/>
        <xs:attribute name="temperature" type="xs:float" use="required"/>
        <xs:attribute name="temperatureUnit" use="required">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="K"/>
              <xs:enumeration value="mK"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:complexType>
    </xs:element>
    </xs:sequence>
    <xs:attribute name="arrayID" type="xs:string" use="required"/>
  </xs:complexType>
</xs:element>
</xs:schema>

=== shirolab/roach2pcp/pcp/testing/tonelists/tonelist_tbexample.xml
<?xml version="1.0" encoding="UTF-8"?>

<tonefile arrayID="MUSCAT25nm-D2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="xmlschema_tbexample.xsd">
	<tonelist ID="001" date="2018-07-26" temperature="0.15" temperatureUnit="K">
		<KID ID="KID001">
			<freq>836.2135</freq>
			<freqUnit>MHz</freqUnit>
			<power>-60</power>
			<powerUnit>dBm</powerUnit>
			<Qfactor>1000000</Qfactor>
		</KID>
		<KID ID="KID002">
			<freq>1.213452</freq>
			<freqUnit>GHz</freqUnit>
			<power>-91</power>
			<powerUnit>dBW</powerUnit>
			<Qfactor>10000</Qfactor>
		</KID>
	</tonelist>
	<tonelist ID="002" date="2018-07-25" temperature="350" temperatureUnit="mK">
		<KID ID="KID001">
			<freq>836.2101</freq>
			<freqUnit>MHz</freqUnit>
			<power>-98</power>
			<powerUnit>dBW</powerUnit>
			<Qfactor>936542</Qfactor>
		</KID>
		<KID ID="KID002">
			<freq>1203452000</freq>
			<freqUnit>Hz</freqUnit>
			<power>-96</power>
			<powerUnit>dBm</powerUnit>
			<Qfactor>95425</Qfactor>
		</KID>
	</tonelist>
</tonefile>
